### ISSUE TITLE
error with python 3.5

### ISSUE THREAD

**Issue by KarlosW** [absortium/poloniex-api#1]
Traceback (most recent call last):
  File "async.py", line 26, in <module>
    app.run()
  File "poloniex-api/poloniex/app.py", line 81, in run
    self.init_api(self.loop, session)
  File "poloniex-api/poloniex/app.py", line 68, in init_api
    stop_decorator(self.main, self.push)()
  File "/usr/lib64/python3.5/site-packages/asyncio-3.4.3-py3.5.egg/asyncio/tasks.py", line 567, in gather
    fut = async(arg, loop=loop)
  File "/usr/lib64/python3.5/site-packages/asyncio-3.4.3-py3.5.egg/asyncio/tasks.py", line 516, in async
    raise TypeError('A Future or coroutine is required')
TypeError: A Future or coroutine is required
sys:1: RuntimeWarning: coroutine 'AsyncApp.init_api.<locals>.stop_decorator.<locals>' was never awaited
sys:1: RuntimeWarning: coroutine 'WAMPClient.start' was never awaited

**Comment by AndrewSamokhvalov** [comment]
@KarlosW, Could you please attach the code which cause this error? Thanks.

**Comment by KarlosW** [comment]
It's the async.py from the examples.

**Comment by Vadus** [comment]
it's still the same behavior with python 3.5

**Comment by kickedinthehead** [comment]
@AndrewSamokhvalov You need to remove the (outdated) 'asyncio' library from the list of dependencies at least for the latest Python version. Otherwise the integrated asyncio library is shadowed by the outdated one which is not compatible with your code (at least not with Python 3.5 or 3.6).

@KarlosW @Vadus Quick fix: pip3 uninstall asyncio
