### ISSUE TITLE
AttributeError: 'WebSocketError' object has no attribute 'encode'

### ISSUE THREAD

**Issue by minhdanh** [absortium/poloniex-api#13]
I'm having this random error when running the async example:

```
Traceback (most recent call last):
  File "a.py", line 45, in <module>
    app.run()
  File "/Projects/misc/poloniex-api/poloniex/app.py", line 80, in run
    self.init_api(self.loop, session)
  File "/Projects/misc/poloniex-api/poloniex/app.py", line 70, in init_api
    loop.run_until_complete(g)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/Projects/misc/poloniex-api/poloniex/wamp/client.py", line 100, in start
    wamp_msg = self.recv(ws_msg.data)
  File "/Projects/misc/poloniex-api/poloniex/wamp/client.py", line 83, in recv
    messages = self.serializer.unserialize(s.encode())
AttributeError: 'WebSocketError' object has no attribute 'encode'
```

Here's what WebSocketError object look like:

```
WSMessage(type=<WSMsgType.ERROR: 258>, data=WebSocketError('Received frame with non-zero reserved bits',), extra=None)
```

**Comment by jam-lock** [comment]
I'm having the same issue, but only on my raspberry pi.

**Comment by jam-lock** [comment]
I tried using python 3.5.1 instead of 3.6.1 on the RPI and it's working since then. Usually it would crash within minutes. I also use python 3.5.1 on the desktop.

**Comment by jam-lock** [comment]
Got the AttributeError again. Did you find a solution or workaround?

**Comment by minhdanh** [comment]
Hi @jam-lock, here is my workaround. It's kind of hacky.

```
diff --git a/poloniex/wamp/client.py b/poloniex/wamp/client.py
index f9d517f..1222be3 100644
--- a/poloniex/wamp/client.py
+++ b/poloniex/wamp/client.py
@@ -80,8 +80,9 @@ class WAMPClient():
         self.ws.send_str(payload.decode())

     def recv(self, s):
-        messages = self.serializer.unserialize(s.encode())
-        return messages[0]
+        if type(s) is str:
+            messages = self.serializer.unserialize(s.encode())
+            return messages[0]

+            messages = self.serializer.unserialize(s.encode())
+            return messages[0]
-        messages = self.serializer.unserialize(s.encode())
-        return messages[0]
+        if type(s) is str:
+            messages = self.serializer.unserialize(s.encode())
+            return messages[0]

     async def start(self):
         async with self.session.ws_connect(url=self.url,
@@ -97,8 +98,9 @@ class WAMPClient():

             async for ws_msg in ws:
                 wamp_msg = self.recv(ws_msg.data)
-                wamp_handler = self.get_handler(wamp_msg.MESSAGE_TYPE)
-                await wamp_handler(wamp_msg)
+                if wamp_msg is not None:
+                    wamp_handler = self.get_handler(wamp_msg.MESSAGE_TYPE)
+                    await wamp_handler(wamp_msg)
```

**Comment by jam-lock** [comment]
Thanks @minhdanh! That handled the issue

**Comment by AndrewSamokhvalov** [comment]
Hey guys! Sorry for not being responsive, have no time to maintain this library, at least for now, I would be appreciated if someone created `PR` to fix the issue.
